### ISSUE TITLE
Process keeps running after window has been closed

### ISSUE THREAD

**Issue by phfaist** [klatexformula/klatexformula#17]
[auto-migrated] Reported by **lujomu** on sf.net [klatexformula/bugs/17](https://sourceforge.net/p/klatexformula/bugs/17)

The title says it all. Whenever I close KLatexFormula, the window disappears, but its process keeps running and I have to kill it via Task Manager.

Please let me know if you need me to provide any more information.

Setup:
KLatexFormula v3.2.8 and v3.3.0beta
Windows 8.1 x64

**Comment by phfaist** [comment]
[closing old issue with no updates, feel free to re-open with additional information if still relevant]

**Comment by user234683** [comment]
I can confirm this is still an issue. I can also confirm that using the "Quit" button closes the process correctly.

System: Debian 10.4
KLatexFormula version: 4.1.0 (compiled from source). This issue also affects version 4.0.0 from the Debian package.

**Comment by phfaist** [comment]
Thanks for reporting. This seems to depend on the Qt version. On my Mac, when I close the window the process closes correctly if I compile with Qt 5.14 but not if I compile with Qt 5.7. I'll investigate.

**Comment by phfaist** [comment]
Ok, I think I found the issue now. I've pushed a fix, it will make it in the next version of klatexformula.
