### ISSUE TITLE
Some issues with inkscape when trying to copy or exporting via inkscape

### ISSUE THREAD

**Issue by SignificantCell2** [klatexformula/klatexformula#52]
Hello,
Thank you very much for this amazing software.
I've compiled it on Ubuntu 20.04, it works fine, except that there are some issues when trying to drag or copy. the scripts used by klatexformula try to convert to emf using inkscape but that fails: if I am not mistaken , that's because inkscape 1.0 changed the command line syntax. Here is an example, when I write a formula and I "Copy" it, then paste it in inkscape:
* Inkscape crashes,
and in the terminal I get the following error message (below is the full content of my terminal):

```
klatexformula
KLatexFormula Version 4.1.0 by Philippe Faist (c) 2005-2017
Licensed under the terms of the GNU General Public License (GPLv2+)

Warning: libpng warning: iCCP: known incorrect sRGB profile
Warning: libpng warning: iCCP: known incorrect sRGB profile
Warning: libpng warning: iCCP: known incorrect sRGB profile
Warning: libpng warning: iCCP: known incorrect sRGB profile
Warning: ***** In function KLFUserScriptExporter::getData()  8/22/20 12:00 AM *****
        Error: Error running user script inkscapeformats: <p><b>User Script /usr/local/share/klatexformula/userscripts/inkscapeformats.klfuserscript</b> reported an error (exit status 1). Here is full stderr output:</p>
<pre>
Using inkscape path: /usr/bin/inkscape
Converting file /tmp/klftmpexporter4x1x0xMOIjTy.pdf

Traceback (most recent call last):
  File "/usr/local/share/klatexformula/userscripts/inkscapeformats.klfuserscript/inkscapeformats.py", line 98, in &lt;module&gt;
    ], shell=False, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/inkscape', '/tmp/klftmpexporter4x1x0xMOIjTy.pdf', '--export-emf=/tmp/klftmpexporter4x1x0xMOIjTy.emf']' returned non-zero exit status 1
</pre>
```

Here is a recording on how to reproduce that error message:

![klatex_formula](https://user-images.githubusercontent.com/67183566/90939917-46b20100-e40d-11ea-9c98-08b1c017f2b3.gif)

Another, note is that it still uses python2 that is deprecated, and the scripts should be ported to Python3 instead.

Thank you very much

**Comment by phfaist** [comment]
Thanks for reporting and sorry for taking me this long to respond. In a few recent commits I've updated the inkscape-formats user script to support both the old and the new inkscape option formats.

If you still get errors, go to *Settings* → *Scripts* → *inkscapeformats.klfuserscript* -> *Script Settings* and click on *Re-detect default settings*.

The user scripts work both on python2 and python3. Klatexformula will use the interpreter it can find. In a recent commit I changed the search procedure so that it prefers python3 over python2.
