### ISSUE TITLE
Warning: libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by TobiasWinchen** [klatexformula/klatexformula#56]
The warning `Warning: libpng warning: iCCP: known incorrect sRGB profile` is displayed on debian. The reason for this is that some pngs shipped with klf have embedded ICC profiles about which libpng complains, see also: 

https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile
 
Using mogrify on all pngs as suggested in the linked discussion fixes the issue.

**Comment by phfaist** [comment]
These warnings were always bugging me but I never managed to identify their source! Thanks for locating their source and for the issue. Should be resolved in the recent commit.
