### ISSUE TITLE
Wrong python interpreter found on debian 

### ISSUE THREAD

**Issue by TobiasWinchen** [klatexformula/klatexformula#57]
As the default python interpreter is python3 in e.g. debian,  `/usr/bin/python-argcomplete-check-easy-install-script3` (or possibly an other program) is found if installed. 

A possible solution is to specify the default python interpreter with cmake using the FindPython / FindPython3 cmake module.

**Comment by phfaist** [comment]
Hi, thanks for reporting this. I've tried to improve the detection mechanism to always prefer an exact match to "python3" or "python2" in a recent commit. Let me know if the python detection is still problematic, and I can try to add an interface to specify the python interpreter via cmake (with defaults via FindPython etc. as you suggest).
