### ISSUE TITLE
Font size appears to have gone microscopic (on the UI itself)

### ISSUE THREAD

**Issue by BrightBulb123** [klatexformula/klatexformula#63]
I installed KLatexFormula just yesterday and it worked wonderfully. Then come the next day and it's decided to go subatomic on me. This is what I'm facing:
![image](https://user-images.githubusercontent.com/83759628/131234150-2dcb6bac-0538-43d3-b68f-f0834fe5f2a8.png)
The actual _LaTeX_ renders out great, but it's just the UI issue that bugs me...

**Comment by phfaist** [comment]
KLatexFormula tries to figure out a nice LaTeX font to set on its own UI. Apparently this doesn't work sometimes. That's some old code and I need to test it again on more recent systems. Which OS are you running? To change the application font, select "settings" (middle of the bottom right pane, it's the button on the left of the question mark), and then select "Advanced" -> "Appearance" -> and select one of the presets for the application font (cf attached screenshot on mac os x). Hope this helps.
<img width="542" alt="Screen Shot 2021-08-29 at 5 34 10 PM" src="https://user-images.githubusercontent.com/2291140/131256371-72310e4e-5a08-4ea2-9425-565e6b6cb8f0.png">

**Comment by BrightBulb123** [comment]
> Which OS are you running?

Here's my OS information (copied from settings):
Edition	Windows 10 Pro
Version	21H1
Installed on	‎10/‎07/‎2021
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

If you want info on my system as well, reply and I can provide that too.

And also, your proposed solution worked; thanks!

**Comment by phfaist** [comment]
Thanks for your quick answer! I'll have to re-test my old code on newer Windows systems.

**Comment by BrightBulb123** [comment]
Mind you, what version of Windows _were_ you using?

**Comment by phfaist** [comment]
I've been testing and compiling klatexformula on an old XP virtual environment (I didn't have access to newer versions, plus I figured that would provide best backwards compatibility).

**Comment by BrightBulb123** [comment]
Ah well, Windows 11 is gonna screw you over then...

**Comment by ruvilecamwasam** [comment]
I was also having this issue on Windows 11. For people who end up here from Google, a fix is provided [here](https://sourceforge.net/p/klatexformula/bugs/32/).

Go to the `klatexformula.conf` file, which on Windows is located at `C:\Users\[username]\.klatexformula`. Then search for _usesystemfont_, and set it to _true_:
`usesystemfont=true`

Next time you open klatexformula the text should be fine.
